#!/bin/sh
FWTOOL=/sbin/iptables
if [ $# -lt 2 ]; then
	echo -e "usage\n $0 <dstip> <0/1>\n0-remove rule, 1-add rule"
	exit;
fi
DSTIP=$1
opt=""
case $2 in
 	0)
 	opt="-D"
 	;;

 	1)
 	opt="-A"
	;;

	 *)
	  echo "wrong option";
	  exit
	;;
esac
${FWTOOL} ${opt} INPUT -j DROP -p tcp --destination-port 80 -d ${DSTIP}
${FWTOOL} -L
